- name: Set service state
  service:
    name: "{{ '{{' }} item {{ '}}' }}"
    enabled: "{{ '{{' }} {{ cookiecutter.name }}_enabled {{ '}}' }}"
    state: "{{ '{{' }} {{ cookiecutter.name }}_enabled | ternary('started', 'stopped') {{ '}}' }}"
  loop: "{{ '{{' }} {{ cookiecutter.name }}_services {{ '}}' }}"
